name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Ver la hora
      run: date

    - name: Esperar 3 segundos
      run: sleep 3

    - name: Que versión tengo en git actualmente
      run: git version

    - name: Voy a ver si está disponible la página de AS
      run: curl -k "https://as.com"